### ISSUE TITLE
New screenshot of nearby places with icons

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/commons-app.github.io#11]
As soon as the icons are implemented the screenshot of the nearby-places screen should be replaced.

**Comment by misaochan** [comment]
Hi @tobias47n9e ,

I just released a version of the app with the new icons, so it should be available within a couple of hours from now. :)

**Comment by tobias47n9e** [comment]
Thanks for the reminder. I will still wait until the list shows some more symbols and labels. Otherwise  we might get a lot of complaints about the information missing.

**Comment by misaochan** [comment]
I honestly don't think the fix for that will be soon (unless someone else is willing to take it on ;)) - it's a pretty big change to switch from reading a CSV file to querying an API. I'm still looking for solutions and will submit it in my IEG renewal proposal at the end of the year, but I don't think I can fit it in before then without removing other tasks that have been planned for this IEG round.

**Comment by maskaravivek** [comment]
We have revamped the whole nearby experience and IMO we can update the screenshots with the new ones.

**Comment by sivaraam** [comment]
@maskaravivek Is this somewhat stable and not about to change anytime soon? Or is there any change in progress which might affect the screen shots if I change them today?

**Comment by maskaravivek** [comment]
It should not change in near future. It would be great if you can update them. :)

**Comment by sivaraam** [comment]
@maskaravivek Just installed the production release from play store. It seems to be v2.8.5 and not v2.9. It seems v2.9 of the app hasn't been released yet (considering you were mentioning the revamp in v2.9 in [your comment](https://github.com/commons-app/commons-app.github.io/issues/11#issuecomment-453040389)). So, I think the screen shots can't be updated now as they won't reflect the stable app available in play store.

Or am I missing something?

**Comment by sivaraam** [comment]
Note to self that #19 could be partially fixed when this gets fixed.

**Comment by maskaravivek** [comment]
> @maskaravivek Just installed the production release from play store. It seems to be v2.8.5 and not v2.9. It seems v2.9 of the app hasn't been released yet (considering you were mentioning the revamp in v2.9 in [your comment](https://github.com/commons-app/commons-app.github.io/issues/11#issuecomment-453040389)). So, I think the screen shots can't be updated now as they won't reflect the stable app available in play store.
> 
> Or am I missing something?

You are right. If you want, you can create a PR with the updated screenshots. The release should happen by next week. Your changes can be merged post that. :)

**Comment by sivaraam** [comment]
I think I'll just update them after the release happens to make sure the screen shot reflect reality and there isn't anything misleading :-)

**Comment by sivaraam** [comment]
I'll learn about the release myself when I get an update. If possible you could also ping me when the app gets released :-)

**Comment by sivaraam** [comment]
@maskaravivek From the [releases page of the app ](https://github.com/commons-app/apps-android-commons/releases) it seems the v2.10.1 itself has been released but the play store version still seems to be stuck at v2.8.5.

Why is this?

**Comment by maskaravivek** [comment]
It has been released only for beta users. Next week it would be released for everyone. :)

**Comment by misaochan** [comment]
2.10.2 was just pushed to production on the play store today. :)

**Comment by sivaraam** [comment]
I got some screen shots for the new version to **replace** the old ones we see in the website. As the new release has some new features, should we highlight them too?

I think of highlighting the 'Explore' section and it's search. Is anyone thinking of anything else that should be highlighted in the website?

**Comment by misaochan** [comment]
Highlighting Explore would be fantastic. Achievements (accessed via the trophy icon next to your username in the nav drawer) could be worth a mention, too. Thanks @sivaraam . :)

**Comment by sivaraam** [comment]
> Achievements (accessed via the trophy icon next to your username in the nav drawer) could be worth a mention, too.

I managed to get a screen shot of it but I faced an issue while doing so. See https://github.com/commons-app/apps-android-commons/issues/2691.

I think we could highlight it after that issue is resolved?
