### ISSUE TITLE
Update web presence

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/commons-app.github.io#13]
We have information about the app scattered in a few places on the internet. Each place has its own set of things that should be included and kept up to date:
- https://commons.wikimedia.org/wiki/Commons:Mobile_app
- https://commons.wikimedia.org/wiki/Commons:Mobile_app/Download
- https://www.mediawiki.org/wiki/Wikimedia_Apps/Commons

In this issue we can discuss some editing strategy and where to put what information.

Should we convert the pages on Commons to just 1 page? The /Download page has very little information and it is not real Wiki-content, but better suited for our new landing page.

**Comment by nicolas-raoul** [comment]
My suggested strategy:

    https://commons.wikimedia.org/wiki/Commons:Mobile_app
Make a big link to the website, remove user-oriented info, keep supervision info

    https://commons.wikimedia.org/wiki/Commons:Mobile_app/Download
Leave as deprecated

    https://www.mediawiki.org/wiki/Wikimedia_Apps/Commons
Leave as is, it is part of the "technology inventory" of Wikimedia, not intended for users to read.

**Comment by nicolas-raoul** [comment]
Fixed https://commons.wikimedia.org/wiki/Commons:Mobile_app

**Comment by misaochan** [comment]
First link looks good to me.

Should we point to the first link from the deprecated link? (Or maybe there is already a link that I am missing?)

**Comment by nicolas-raoul** [comment]
I made that page a redirect to Commons:Mobile_app

**Comment by sivaraam** [comment]
Is there anything left to do for this issue?

**Comment by nicolas-raoul** [comment]
I updated and redirected more.
I believe this is OK now, if not feel free to reopen.
