### ISSUE TITLE
"Get it on F-Droid" badge

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/commons-app.github.io#14]
Just _above_ "Get it on Google Play" :-)

[<img src="https://f-droid.org/badge/get-it-on.png">](https://f-droid.org/app/fr.free.nrw.commons)

**Comment by tobias47n9e** [comment]
Thanks for the reminder. I added the badge.

**Comment by tobias47n9e** [comment]
And I will still add a second button in the first section or think of another way to add those links.

**Comment by tobias47n9e** [comment]
@domdomegg Added the second button. Thanks!

**Comment by domdomegg** [comment]
No problemo :)
