### ISSUE TITLE
Migrate to Wmflabs

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/commons-app.github.io#18]
I am in the process of migrating the website to wmflabs:
- https://wikitech.wikimedia.org/wiki/Commons-App-Web

Some open questions:
- How to redirect from the current page?
- Where do links need to be changed to point to the new page?

**Comment by nicolas-raoul** [comment]
Hi Tobias,

The SPARQL request builder will indeed be happy to fin its home there, thanks!

About the user-facing website now at http://commons-app.github.io though, what are the benefits of moving it there? I worry we might have less control on it, and the URL is not great (commons-app.github.io
is a nice URL as it conveys the app's name and the fact that it is open source in 21 characters instead of 34)

Cheers!

**Comment by tobias47n9e** [comment]
The URL is indeed a downside. 

If we want to make the landing page translatable we need to handle the language in the request. Not sure we can do that elegantly within the Github pages (either fetching or redirecting).

We could also buy a domain for the wmflabs page, which would also give us a shorter URL.

**Comment by nicolas-raoul** [comment]
I don't think buyixg a domain is worth the complexity of managing to never
get cybersquatted in the future, among other complexities.
How about a dead-simple template-based script that generates static HTML?
French would be at /fr, German at /de, etc. Google would soon learn to
direct people to the right one. We should also have a language dropdown
anyway.
Cheers!

**Comment by domdomegg** [comment]
Is this done? Seems to be located here now:
https://tools.wmflabs.org/commons-app-web/en/

The translations are all English and the links between them don't work properly, but think that's another issue

**Comment by tobias47n9e** [comment]
@domdomegg the website on labs is just a test at this point. I might take it outline again until we know what to do next and if we even want to go the path of a framework

**Comment by tobias47n9e** [comment]
I shut down the page on wmflabs for now.

**Comment by domdomegg** [comment]
K cool. Not sure on what official policy is but maybe it could redirect to github pages site?

**Comment by tobias47n9e** [comment]
I think not many people were even aware of that URL, so the redirect might not be worth setting up.

**Comment by domdomegg** [comment]
Ah sure, sounds sensible :)

**Comment by sivaraam** [comment]
Is the consensus that we're not migrating to WMF labs? Or is migration stille being considered?

**Comment by domdomegg** [comment]
@sivaraam I think the consensus is that we're not moving.

**Comment by sivaraam** [comment]
So, can we just close this one?
