### ISSUE TITLE
Migrating to bootstrap?

### ISSUE THREAD

**Issue by domdomegg** [commons-app/commons-app.github.io#20]
As the title says, do you think it's worth migrating to bootstrap - should be pretty easy with what's on the site currently and could be easier to maintain in the future, especially if thinking of transferring to a web framework. Currently seems to be loads of CSS code that whilst including bootstrap would remove most of it and end up looking identical, or very similar at least.

**Comment by tobias47n9e** [comment]
We could look into that if we expand the page at some point. At the moment I think we can just maintain it until we know what to do next.

**Comment by domdomegg** [comment]
Gonna close this issue, as not really an 'issue', made this quickly just to kinda see what it's like:
https://github.com/domdomegg/commons-app.github.io/tree/bootstrap

**Comment by tobias47n9e** [comment]
I will gladly merge it if it makes further development of the page easier. Is there anything else that you think needs improvement?

**Comment by domdomegg** [comment]
Reopening as potentially going to submit a PR to migrate to boostrap.

**Comment by domdomegg** [comment]
There are a few things that I would like to improve upon - will create a list in a minute

**Comment by domdomegg** [comment]
See PR #21
