### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by misaochan** [commons-app/commons-app.github.io#22]
Would it be possible to update the screenshots shown on the website? The upload screen ("Upload your files anywhere") in particular has changed a lot recently.

**Comment by misaochan** [comment]
Bumping this as the app looks very different now, especially the new Nearby. :)

**Comment by sivaraam** [comment]
@misaochan Right. Would you like to give the new screenshots? I thought you would have a better idea as to what should be used for the showcase.

Or should I just pick them, myself?

**Comment by nicolas-raoul** [comment]
@sivaraam Feel free to propose screenshots by sending pull requests towards https://github.com/commons-app/apps-android-commons/tree/master/design/screenshots
Cheers!
