### ISSUE TITLE
Add QR code

### ISSUE THREAD

**Issue by whym** [commons-app/commons-app.github.io#23]
When introducing the app to others, it would be nice to able to load the page on your phone and show it to others for scanning - Split from https://github.com/commons-app/apps-android-commons/issues/536#issuecomment-300416491

An example is:
![commonsapp](https://cloud.githubusercontent.com/assets/10674/25806962/155aa1c8-3440-11e7-99c9-b2ef9b740f6f.png)
This should link to http://commons-app.github.io.

**Comment by tobias47n9e** [comment]
Good idea. I added it.
