### ISSUE TITLE
Switch to bootstrap v4.1 stable?

### ISSUE THREAD

**Issue by sivaraam** [commons-app/commons-app.github.io#29]
Bootstrap v4 alpha has been outdated according to [the website](https://v4-alpha.getbootstrap.com/). How about switching to the stable v4.1?

**Comment by nicolas-raoul** [comment]
@sivaraam Yes sure :-)
Do you want to do it?

**Comment by sivaraam** [comment]
> Do you want to do it?

Sure, when I get time! I would going out of town for a week. So, I'll try to do it when I find time.

**Comment by sivaraam** [comment]
I have a little doubt now. Do we require the navbar? Given that,

1. The page it self is not too long and
1. All the links in the navbar link only to different sections of the page and
1. The navbar seems to be the only component requiring javascript

Should we better remove the navbar? Removing it would make the page become independent of the javascript resources which might in turn reduce the load time.

**Comment by misaochan** [comment]
I personally find the nav bar very helpful, especially if we plan on expanding the page's content in the future. But I'm not a web dev. :)

**Comment by sivaraam** [comment]
In that case, I'll keep the resolution for this focused only for switching to v4.1 and I'll see if I could do something about the navbar separately.
