### ISSUE TITLE
Add link (on Google Play page, etc) to this website when ready

### ISSUE THREAD

**Issue by misaochan** [commons-app/commons-app.github.io#3]
Love the website so far @tobias47n9e ! Do let me know when it's ready to be published, and I'll add the link on our Google Play page and such. :)

**Comment by tobias47n9e** [comment]
Thanks. We should maybe decide on some more content and plan to add the link sometime next week? I am thinking of just having the one page version and leaving the translations for when we run a proper framework.

**Comment by nicolas-raoul** [comment]
Yes, we don't really need internationalization right now... even the app is not i18ed yet :-/

**Comment by misaochan** [comment]
Yeah, we can definitely publish before the translations are done I think. Next week sounds good to me, probably after the documentation is added?

**Comment by misaochan** [comment]
Aside from the Google Play page, I guess we could also add the link to the About activity and our github Readme? Anything else that I'm missing?

**Comment by misaochan** [comment]
The website link has been added to About activity. I will add it to Google Play and GitHub readme tomorrow if there are no objections?

**Comment by nicolas-raoul** [comment]
No objections from me, anytime is fine :-)

**Comment by misaochan** [comment]
Added to GitHub and Google Play (will take a few hrs for update to go through).

**Comment by misaochan** [comment]
I'll close this, feel free to reopen if there is anywhere else you'd like the link on.
