### ISSUE TITLE
Add documentation page

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/commons-app.github.io#4]
Cut-and-paste content from https://github.com/commons-app/apps-android-commons/wiki#user-documentation
That could include screenshots too :-)

**Comment by tobias47n9e** [comment]
Sounds good. Will try to get something done later this week.

**Comment by mithlesh4257** [comment]
Should I need to add user, developer, contributor Documentation right?
@nicolas-raoul

**Comment by nicolas-raoul** [comment]
@mithlesh4257 No, just the "User" part (two pages) :-)

**Comment by Vishal-raj-1** [comment]
@nicolas-raoul Sir should I include the content of this two files ? 
![add](https://user-images.githubusercontent.com/59874304/104720923-23d51000-5753-11eb-8d75-feabb4f2b865.JPG)

**Comment by nicolas-raoul** [comment]
Content to add:
- https://github.com/commons-app/commons-app-documentation/blob/master/android/How-to-install-and-use-the-app.md except the "How to install and use the app" section.
- https://github.com/commons-app/commons-app-documentation/blob/master/android/Getting-app-logs-from-Android-Studio.md

It could be either a separate page, or a new section at the bottom (after "Photo Guidelines"). Not sure what is best. Having everything on the same page would make it double its current size, and include very arcane details, so I guess a separate page is better? It could be called "Tips".

**Comment by Vishal-raj-1** [comment]
> so I guess a separate page is better? It could be called "Tips".

Yes !! I would like to add documentation in different page. May I go for this assignment @nicolas-raoul Sir ?

**Comment by nicolas-raoul** [comment]
No news from Mithlesh4257 since 2018, so yes it's yours @Vishal-raj-1 thanks!
