### ISSUE TITLE
Make a Footer for the website navigating to the organisations main github profile

### ISSUE THREAD

**Issue by lopeselio** [commons-app/commons-app.github.io#46]

**Comment by Vishal-raj-1** [comment]
@lopeselio May I go for this issue ?

**Comment by nicolas-raoul** [comment]
I don't think this is needed, as there is already a "Source code" button linking to GitHub.

**Comment by Vishal-raj-1** [comment]
> I don't think this is needed, as there is already a "Source code" button linking to GitHub.

Link is give for Main profile of organization.

**Comment by nicolas-raoul** [comment]
You are right. I don't think the organization's profile is worth linking to, though, very few users need it, and the ones who need it are already familiar with the main project.
