### ISSUE TITLE
adding shadow to features items

### ISSUE THREAD

**Issue by Vishal-raj-1** [commons-app/commons-app.github.io#48]
It will look awesome.

## Preview 

![shadow](https://user-images.githubusercontent.com/59874304/104726916-7a921800-575a-11eb-8d84-a8678650da3c.JPG)

@nicolas-raoul should I go for this changes. one more change that I want is make adding little transformation on hovering on features images.

**Comment by nicolas-raoul** [comment]
Anyone into web design has an opinion on whether this is a good idea?
